#!/usr/bin/env perl
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/lib", "$FindBin::Bin/local/lib/perl5";

use Plack::Runner;

use File::Basename;
use File::Spec;
use Cwd;

{


  my $runner = Plack::Runner->new;
  $runner->parse_options(@ARGV);
  local $ENV{CLAUDE_PROJECTS_DIR} = shift(@{$runner->{argv}}) || getcwd;

  $runner->run;
}

sub usage {
  die <<END;
Usage: @{basename($0)} ?DIR?
END
}
